### ISSUE TITLE
Góp ý cập nhật cho phần Document

### ISSUE THREAD

**Issue by lavisar** [DH-Pub/project4#1]
1 Documnet nên có những thư mục và thư mục sẽ có những file con

em nghĩ nên tạo thêm 1 bảng file để nối với bảng document theo hướng 1 document có nhiều file

example: 
![image](https://github.com/DH-Pub/project4/assets/67550867/01a14b7b-24a1-4739-8470-8a040052ee6f)

**Comment by DH-Pub** [comment]
1 project có nhiều documents rồi mà, vì vậy mới để bảng documents với foreign key project_id
